export const UPDATE_MAX = 'UPDATE_MAX';
export const CALCULATE_PERCENTAGES = 'CALCULATE_PERCENTAGES';
export const UPDATE_ACTIVE = 'UPDATE_ACTIVE';
export const RESET = 'RESET';
export const SELECT_WEIGHT = 'SELECT_WEIGHT';